// Code generated by protoc-gen-go.
// source: pb/mudah.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/mudah.proto

It has these top-level messages:
	GetRequest
	GetReply
	SetRequest
	SetReply
	ListRequest
	ListReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetReply struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *GetReply) Reset()                    { *m = GetReply{} }
func (m *GetReply) String() string            { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()               {}
func (*GetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SetRequest struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SetReply struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *SetReply) Reset()                    { *m = SetReply{} }
func (m *SetReply) String() string            { return proto.CompactTextString(m) }
func (*SetReply) ProtoMessage()               {}
func (*SetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ListRequest struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ListReply struct {
	Values []*GetReply `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *ListReply) Reset()                    { *m = ListReply{} }
func (m *ListReply) String() string            { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()               {}
func (*ListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListReply) GetValues() []*GetReply {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "mudahkv.GetRequest")
	proto.RegisterType((*GetReply)(nil), "mudahkv.GetReply")
	proto.RegisterType((*SetRequest)(nil), "mudahkv.SetRequest")
	proto.RegisterType((*SetReply)(nil), "mudahkv.SetReply")
	proto.RegisterType((*ListRequest)(nil), "mudahkv.ListRequest")
	proto.RegisterType((*ListReply)(nil), "mudahkv.ListReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for MudahKV service

type MudahKVClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetReply, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
}

type mudahKVClient struct {
	cc *grpc.ClientConn
}

func NewMudahKVClient(cc *grpc.ClientConn) MudahKVClient {
	return &mudahKVClient{cc}
}

func (c *mudahKVClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := grpc.Invoke(ctx, "/mudahkv.MudahKV/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mudahKVClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetReply, error) {
	out := new(SetReply)
	err := grpc.Invoke(ctx, "/mudahkv.MudahKV/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mudahKVClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := grpc.Invoke(ctx, "/mudahkv.MudahKV/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MudahKV service

type MudahKVServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
	Set(context.Context, *SetRequest) (*SetReply, error)
	List(context.Context, *ListRequest) (*ListReply, error)
}

func RegisterMudahKVServer(s *grpc.Server, srv MudahKVServer) {
	s.RegisterService(&_MudahKV_serviceDesc, srv)
}

func _MudahKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MudahKVServer).Get(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _MudahKV_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MudahKVServer).Set(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _MudahKV_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(MudahKVServer).List(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _MudahKV_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mudahkv.MudahKV",
	HandlerType: (*MudahKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MudahKV_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _MudahKV_Set_Handler,
		},
		{
			MethodName: "List",
			Handler:    _MudahKV_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x48, 0xd2, 0xcf,
	0x2d, 0x4d, 0x49, 0xcc, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0x73, 0xb2, 0xcb,
	0x94, 0x24, 0xb9, 0xb8, 0xdc, 0x53, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xb8,
	0xb9, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x95, 0xd4, 0xb8, 0x38, 0xc0,
	0x52, 0x05, 0x39, 0x95, 0x28, 0x12, 0x42, 0xbc, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12,
	0x4c, 0x60, 0x75, 0x1a, 0x5c, 0x5c, 0xc1, 0xd8, 0x8d, 0x40, 0x57, 0x09, 0x34, 0x31, 0x98, 0x18,
	0x13, 0x65, 0xb9, 0xb8, 0x7d, 0x32, 0x8b, 0xe1, 0x46, 0xf2, 0x71, 0xb1, 0x15, 0x14, 0xa5, 0xa6,
	0x65, 0x56, 0x40, 0x1d, 0xa6, 0xc7, 0xc5, 0x09, 0x91, 0x06, 0x99, 0xa3, 0xc8, 0xc5, 0x06, 0xd6,
	0x5a, 0x0c, 0x94, 0x64, 0xd6, 0xe0, 0x36, 0x12, 0xd4, 0x83, 0x7a, 0x4d, 0x0f, 0xe6, 0x78, 0xa3,
	0xf9, 0x8c, 0x5c, 0xec, 0xbe, 0x20, 0x41, 0xef, 0x30, 0x21, 0x7d, 0x2e, 0x66, 0xa0, 0xb8, 0x90,
	0x30, 0xaa, 0x2a, 0xb0, 0x3d, 0x52, 0x98, 0x5a, 0x95, 0x18, 0x40, 0x1a, 0x82, 0x51, 0x34, 0x04,
	0x63, 0xd3, 0x10, 0x8c, 0xd0, 0x60, 0xc4, 0xc5, 0x02, 0x72, 0x9d, 0x90, 0x08, 0x5c, 0x12, 0xc9,
	0x2f, 0x52, 0x42, 0x68, 0xa2, 0x60, 0x3d, 0x4e, 0x2c, 0x51, 0x4c, 0x05, 0x49, 0x49, 0x6c, 0xe0,
	0xb8, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x4a, 0x9e, 0x40, 0xad, 0x01, 0x00, 0x00,
}
